name: Sync from NPM

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1日 00:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NeteaseCloudMusicApi Repo
        uses: actions/checkout@v4
        with:
          repository: syybi/NeteaseCloudMusicApi
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Delete Unwanted Files and Directories
        run: |
          # 删除指定的目录和文件
          rm -rf data module plugins public util
          rm -f LICENSE app.js generateConfig.js interface.d.ts main.js package.json server.js
          # 提交删除的文件
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "chore: remove unnecessary files and directories" || echo "No changes to commit"
          git push origin main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Get NPM Package Info
        id: npm
        run: |
          LATEST_VERSION=$(npm view NeteaseCloudMusicApi version)
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Download and Extract Package
        run: |
          # 下载并解压到当前目录
          curl -L https://registry.npmjs.org/NeteaseCloudMusicApi/-/NeteaseCloudMusicApi-${{ steps.npm.outputs.version }}.tgz -o package.tgz
          tar -xzf package.tgz --strip-components=1
          rm package.tgz

      - name: Commit New Package Files
        run: |
          # 提交新下载的文件
          git add .
          git commit -m "chore: sync from npm@${{ steps.npm.outputs.version }}" || echo "No changes to commit"
          git push origin main
